name: ros-action-ci
on: [pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu:bionic
            ros_distro: melodic
          - docker_image: ubuntu:focal
            ros_distro: noetic
    container:
      image: ${{ matrix.docker_image }}
    env:
        DISPLAY: :99
    steps:
      - name: Get the code
        uses: actions/checkout@v2
      - run: cp deps.repos /tmp  # copy dep.repos to /tmp to be used later
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.2
        with:
          required-ros-distributions: ${{ matrix.ros_distro }}
      - name: Setup headless xserver with xvfb
        run: apt-get update -y && apt-get install --no-install-recommends -y xvfb mesa-utils && rm -rf /var/lib/apt/lists/*
      - run: Xvfb :99 -screen 0 1024x768x24 +extension GLX +render -noreset >>xsession.log 2>&1 &
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: trajectory_tracking_control
          target-ros1-distro: ${{ matrix.ros_distro }}
          vcs-repo-file-url: "/tmp/deps.repos"  # ensure updated dep.repos from source branch