# Based on https://github.com/ros-industrial/industrial_ci

name: CI-Melodic

on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}