# Based on https://github.com/ros-industrial/industrial_ci

name: CI-Noetic

on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@v0.2
      # - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}